c_compiler:  # [win]
    - vs2017             # [win]
    - vs2017             # [win]
    - vs2017             # [win]

cxx_compiler:  # [win]
    - vs2017             # [win]
    - vs2017             # [win]
    - vs2017             # [win]

MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.12'                # [osx]
