{% set version = "0.6.11" %}

package:
  name: autodiff
  version: {{ version }}

source:
  url: https://github.com/autodiff/autodiff/archive/v{{ version }}.tar.gz
  sha256: ac7a52387a10ecb8ba77ce5385ffb23893ff9a623467b4392bd204422a3b5c09

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - ccache  # [unix]
    - clcache  # [win]

  host:
    - python
    - pip
    - eigen
    - catch2 =2
    - pybind11
    - pybind11-stubgen
    - pybind11-abi

  run:
    - python
    # eigen MUST NOT be added here but installed explicitly by the user if needed

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - autodiff

about:
  home: https://autodiff.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic differentiation in C++ couldn't be simpler.
  doc_url: https://autodiff.github.io
  dev_url: https://github.com/autodiff/autodiff

extra:
  recipe-maintainers:
    - allanleal
