appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
azure:
  settings_win:
    pool:
      vmImage: windows-2019
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
travis:
  secure:
    BINSTAR_TOKEN: iYTQZxbrDJDrr0jatr0nBuwPA+S6yDUA/m8Sg/SfDVIBmt8tesWALLUBdY8oSEqwBPLrdq+0vtonqlAIj+csveySCx6kWy/pR0tA5RUu1PAeBNxLkiFhZe8fxfTBnWhB5mOm+NQcEjNQ/xg9T9JTk27gQVDOK81GOehzLwhPn1TEJ3UYzYBWw6RymUINrZp9FYfi6aIdwGqn65hXetWaM7sRWwztB+6CKneevZdxpjfAt/aBGFzSLdGj2YK4y2mpdUN5Zy9+rCCHihOlZI+pxApqkTHQmYx1Kx9fh4h1xN/MjjKQftTlTqFYw7/vak80cfOKhCYUDI21iiFxne1aLEF66wxnidyUfZWjLe1NDbPjs5p+KeVqGSemnmncr04aWnykije1ijp8cyIwsSxFjcziCrKjIexaseLBGfPDO9mzfDhlldDvfgmbTCSCt330F4U4RJZu1e1vQvl3riTEw4Xz0oOH8yn2HG2B9lZrvnEDFQoyrzcsgrd3D7/l6A59VaJr0IhAsKz8HZEC16TkRq7JbJyvIp7fTSLPo7dJABbt4Ar/o92ET352VGFZ9nFpkhapqrkayyWQlkmskOSqn3GVsf1ZPcUidye1CNOr6U26FOlNEEeEztKBQgOx2g4oQnkxouYmqe7A3CKRInUHACGUg8GnSRBfcU+MTyDh3g0=
